services:
  benchmark:
    image: ocnn-base:v0
    shm_size: 16gb
    network_mode: host
    ipc: host
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NCCL_DEBUG=INFO
      - NCCL_P2P_DISABLE=1
      - OCNN_AUTOTUNE_CACHE_PATH=./.ocnnconvt/autotune_cache.json
      - UV_SYSTEM_PYTHON=1
    working_dir: /workspace
    command:  uv run test/benchmark_conv.py